---

stages:
    - test
    - coverage

Lua 5.3:
    image: alpine:3.12.1
    stage: test
    before_script:
        - apk add lua5.3 luarocks5.3 make
        - luarocks-5.3 install fennel
    script:
        - LUA=lua5.3 make test

Lua 5.4:
    image: ubuntu:20.10
    stage: test
    before_script:
        - ln -snf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
        - echo Europe/Moscow > /etc/timezone
        - apt-get update && apt-get install -y lua5.4 luarocks make >/dev/null
        - luarocks install fennel
    script:
        - LUA=lua5.4 make test

Coverage:
    image: alpine:3.12.1
    stage: coverage
    before_script:
        - apk add lua5.3 lua5.3-dev gcc musl-dev luarocks5.3 make
        - luarocks-5.3 install fennel
        - luarocks-5.3 install luacov
        - luarocks-5.3 install luacov-console
    script:
        - LUA=lua5.3 make luacov-console
        - luacov-console -s
